import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // App Name
    'app.name': 'Farmer Assistant',
    
    // Navbar
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.pricing': 'Pricing',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Home Page - Hero
    'home.hero.badge': 'AI-Powered Farming Intelligence',
    'home.hero.title': 'Empowering Farmers with Smart Crop Management 🌱',
    'home.hero.subtitle': 'Track your crops, manage your stock, and find the best places to grow your business.',
    'home.hero.cta': 'Start Free Trial',
    'home.hero.viewPlans': 'View Subscription Plans',
    
    // Home Page - How It Works
    'home.howItWorks.title': 'How It Works',
    'home.howItWorks.subtitle': 'Simple steps to transform your farming experience',
    'home.step1.title': 'Track Your Crops',
    'home.step1.description': 'Add your crops and monitor their growth cycle with ease',
    'home.step2.title': 'Get Smart Alerts',
    'home.step2.description': 'Receive notifications about low stock and optimal planting times',
    'home.step3.title': 'Connect to Markets',
    'home.step3.description': 'Discover nearby marketplaces to grow your business',
    
    // Home Page - AI Assistant
    'home.ai.badge': 'AI-Powered Assistant',
    'home.ai.title': 'Meet FarmBot - Your 24/7 Farming Companion',
    'home.ai.description': "Ask FarmBot about your crops, get instant weather updates, find marketplaces, or receive personalized recommendations. It's like having an agricultural expert in your pocket.",
    'home.ai.feature1.title': 'Natural language queries',
    'home.ai.feature1.description': 'Ask questions like "When should I plant corn?"',
    'home.ai.feature2.title': 'Real-time insights',
    'home.ai.feature2.description': 'Get instant stock and weather updates',
    'home.ai.feature3.title': 'Personalized recommendations',
    'home.ai.feature3.description': 'Based on your location and season',
    'home.ai.chat.greeting': 'Hi! How can I help you today? 🌱',
    'home.ai.chat.question': 'Check my wheat stock',
    'home.ai.chat.response': 'Your wheat stock is at 80%. You have approximately 2 tons remaining. Would you like suggestions for selling?',
    'home.ai.status': 'Online',
    
    // Home Page - Featured Section
    'home.featured.title': 'Transform Your Farming Experience',
    'home.featured.description': 'Join thousands of farmers who are using technology to improve their crop yields, manage their inventory, and connect with markets. Our platform provides everything you need to succeed in modern farming.',
    'home.featured.getStarted': 'Get Started',
    
    // Home Page - Features
    'home.features.title': 'Everything You Need to Succeed',
    'home.features.subtitle': 'Powerful features designed specifically for modern farmers',
    'home.features.crop.title': 'Crop Insights',
    'home.features.crop.description': 'Track every crop with detailed analytics and growth patterns',
    'home.features.weather.title': 'Weather Integration',
    'home.features.weather.description': 'Real-time weather updates tailored to your location',
    'home.features.market.title': 'Market Suggestions',
    'home.features.market.description': 'Find the best places to buy seeds and sell your harvest',
    'home.features.stock.title': 'Stock Analytics',
    'home.features.stock.description': 'Monitor inventory levels and get smart restock alerts',
    
    // Home Page - Subscription
    'home.subscription.title': 'Choose Your Plan',
    'home.subscription.subtitle': 'Start with a free trial, then select the plan that fits your farming needs',
    'home.subscription.popular': 'Most Popular',
    'home.subscription.getStarted': 'Get Started',
    'home.plan.basic': 'Basic',
    'home.plan.pro': 'Pro',
    'home.plan.premium': 'Premium',
    'home.plan.month': 'month',
    'home.plan.6months': '6 months',
    'home.plan.year': 'year',
    'home.plan.basic.feature1': '1-month access',
    'home.plan.basic.feature2': 'Basic notifications',
    'home.plan.basic.feature3': 'Crop tracking',
    'home.plan.basic.feature4': 'Email support',
    'home.plan.pro.feature1': '6-month access',
    'home.plan.pro.feature2': 'Advanced analytics',
    'home.plan.pro.feature3': 'Weather integration',
    'home.plan.pro.feature4': 'Priority support',
    'home.plan.premium.feature1': '1-year access',
    'home.plan.premium.feature2': 'AI recommendations',
    'home.plan.premium.feature3': 'Market insights',
    'home.plan.premium.feature4': '24/7 priority support',
    
    // Home Page - CTA
    'home.cta.title': 'Ready to Transform Your Farming?',
    'home.cta.subtitle': 'Join thousands of farmers already using Farmer Assistant to grow smarter',
    'home.cta.button': 'Start Your Free Trial Today',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': "Here's what's happening with your crops today",
    'dashboard.totalCrops': 'Total Crops',
    'dashboard.avgStock': 'Avg Stock Level',
    'dashboard.alerts': 'Alerts',
    'dashboard.markets': 'Markets Nearby',
    'dashboard.cropOverview': 'Crop Overview',
    'dashboard.addCrop': 'Add Crop',
    'dashboard.profit': 'Profit',
    'dashboard.profitLocked': 'Profit information is locked',
    'dashboard.upgradeToSeeProfit': 'Upgrade your subscription to view profit calculations',
    'dashboard.aiRecommendation': 'AI Recommendation',
    'dashboard.viewDetails': 'View Details',
    'dashboard.dismiss': 'Dismiss',
    'dashboard.nearbyMarkets': 'Nearby Marketplaces',
    'dashboard.viewMap': 'View Full Map',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.upgradePremium': 'Upgrade to Premium',
    'dashboard.upgradeCta': 'Get AI recommendations and priority support',
    'dashboard.upgradeNow': 'Upgrade Now',
    'dashboard.types': 'Types',
    'dashboard.active': 'Active',
    'dashboard.found': 'Found',
    'dashboard.within': 'Within 15km',
    'dashboard.stockLevel': 'Stock Level',
    'dashboard.good': 'Good',
    'dashboard.low': 'Low',
    'dashboard.critical': 'Critical',
    'dashboard.acrossAll': 'Across all crops',
    'dashboard.requiresAttention': 'Requires attention',
    'dashboard.allGood': 'All good',
    'dashboard.noCrops': 'No Crops Yet',
    'dashboard.noCropsDesc': 'Start tracking your crops by adding your first one',
    'dashboard.alertCriticalStock': 'has critical stock level',
    'dashboard.alertLowStock': 'has low stock level',
    'dashboard.allCropsGood': 'All crops are in good condition',
    'dashboard.activityUpdated': 'updated',
    'dashboard.noAlerts': 'No alerts at this time',
    'dashboard.noActivities': 'No recent activities',
    'dashboard.addFirstCrop': 'Add Your First Crop',
    'dashboard.myCrops': 'My Crops',
    'dashboard.exploreFarms': 'Explore Farms',
    'dashboard.subscription': 'Subscription',
    'dashboard.aiMessage': 'Based on your location and the current season, it\'s an excellent time to plant corn. Weather conditions are optimal, and market demand is high in your area.',
    'dashboard.interactiveMap': 'Interactive map view',
    'dashboard.showingMarkets': 'Showing markets within 15km',
    'dashboard.exploreMap': 'Explore Egypt Farm Map',
    
    // Profile Page
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your personal information and farm details',
    'profile.loading': 'Loading profile...',
    'profile.editProfile': 'Edit Profile',
    'profile.saveChanges': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.cancel': 'Cancel',
    'profile.changePhoto': 'Click to upload profile picture',
    'profile.maxSize': 'Max size: 5MB',
    'profile.acres': 'acres',
    
    // Profile Fields
    'profile.fields.fullName': 'Full Name',
    'profile.fields.email': 'Email Address',
    'profile.fields.phone': 'Phone Number',
    'profile.fields.farmName': 'Farm Name',
    'profile.fields.farmSize': 'Farm Size (acres)',
    'profile.fields.location': 'Location',
    'profile.fields.address': 'Full Address',
    'profile.fields.bio': 'Bio / About Your Farm',
    'profile.fields.bioPlaceholder': 'Tell us about your farming experience...',
    
    // Account Settings
    'profile.accountSettings': 'Account Settings',
    'profile.accountStatus': 'Account Status',
    'profile.active': 'Active',
    'profile.memberSince': 'Member Since',
    'profile.subscriptionPlan': 'Subscription Plan',
    'profile.proPlan': 'Pro Plan',
    'profile.twoFactor': 'Two-Factor Authentication',
    'profile.enable': 'Enable',
    
    // About Page
    'about.hero.title': 'About',
    'about.hero.subtitle': 'We\'re on a mission to empower farmers worldwide with intelligent tools that make crop management simple, efficient, and sustainable.',
    
    // Mission, Vision, Values
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To empower every farmer with technology and insights that help them grow more sustainably and profitably.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'A world where every farmer has access to smart tools that make farming easier, more efficient, and more rewarding.',
    'about.values.title': 'Our Values',
    'about.values.description': 'Sustainability, innovation, and farmer-first thinking guide everything we do.',
    
    // Impact Section
    'about.impact.title': 'Our Impact',
    'about.impact.subtitle': 'Helping farmers around the world achieve better results',
    'about.impact.activeFarmers': 'Active Farmers',
    'about.impact.hectaresManaged': 'Hectares Managed',
    'about.impact.yieldIncrease': 'Avg. Yield Increase',
    'about.impact.wasteReduction': 'Waste Reduction',
    
    // Team Section
    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'A passionate group of experts dedicated to transforming agriculture',
    'about.team.member1.name': 'Sarah Johnson',
    'about.team.member1.role': 'Founder & CEO',
    'about.team.member1.bio': 'Agricultural engineer with 15 years of farming experience',
    'about.team.member2.name': 'Michael Chen',
    'about.team.member2.role': 'Head of AI',
    'about.team.member2.bio': 'AI specialist focused on sustainable agriculture technology',
    'about.team.member3.name': 'Emily Rodriguez',
    'about.team.member3.role': 'Product Lead',
    'about.team.member3.bio': 'Passionate about creating tools that empower farmers',
    'about.team.member4.name': 'David Kumar',
    'about.team.member4.role': 'Head of Support',
    'about.team.member4.bio': 'Dedicated to helping farmers succeed with our platform',
    
    // Sustainability Section
    'about.sustainability.title': 'Committed to Sustainability',
    'about.sustainability.description': 'We believe technology and sustainability go hand in hand. Our platform helps farmers reduce waste, optimize resource usage, and implement more eco-friendly farming practices.',
    'about.sustainability.chemical.title': 'Reduce Chemical Usage',
    'about.sustainability.chemical.description': 'Smart alerts help farmers apply fertilizers and pesticides only when needed',
    'about.sustainability.waste.title': 'Minimize Food Waste',
    'about.sustainability.waste.description': 'Better stock tracking and market connections reduce post-harvest losses',
    'about.sustainability.resources.title': 'Optimize Resources',
    'about.sustainability.resources.description': 'Data-driven insights help farmers use water and energy more efficiently',
    
    // Story Section
    'about.story.title': 'Our Story',
    'about.story.paragraph1': 'was born from a simple observation: farmers work incredibly hard, yet many lack access to the digital tools that could make their lives easier and their businesses more profitable.',
    'about.story.paragraph2': 'Our founder, Sarah Johnson, grew up on a family farm and witnessed firsthand the challenges farmers face daily. After studying agricultural engineering and working in the tech industry, she realized there was a gap between cutting-edge technology and the farming community.',
    'about.story.paragraph3.start': 'Today,',
    'about.story.paragraph3.end': 'serves thousands of farmers worldwide, providing them with AI-powered insights, real-time monitoring, and market connections that help them succeed in an increasingly competitive industry. We\'re just getting started, and we\'re committed to continuously improving our platform based on farmer feedback.',
    
    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have a question or need support? We\'re here to help you succeed.',
    
    // Contact Form
    'contact.form.title': 'Send us a Message',
    'contact.form.firstName': 'First Name',
    'contact.form.lastName': 'Last Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.firstNamePlaceholder': 'John',
    'contact.form.lastNamePlaceholder': 'Farmer',
    'contact.form.emailPlaceholder': 'john@farm.com',
    'contact.form.subjectPlaceholder': 'How can we help you?',
    'contact.form.messagePlaceholder': 'Tell us more about your inquiry...',
    'contact.form.sendButton': 'Send Message',
    
    // Contact Information
    'contact.info.title': 'Contact Information',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.address': 'Address',
    'contact.info.addressLine1': '123 Agriculture Ave',
    'contact.info.addressLine2': 'Farmville, CA 94016',
    
    // Office Hours
    'contact.hours.title': 'Office Hours',
    'contact.hours.mondayFriday': 'Monday - Friday',
    'contact.hours.mondayFridayTime': '9:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.saturdayTime': '10:00 AM - 4:00 PM',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.sundayTime': 'Closed',
    
    // FarmBot CTA
    'contact.farmbot.title': 'Need Instant Help?',
    'contact.farmbot.description': 'Chat with FarmBot, our AI assistant, for immediate answers to common questions.',
    'contact.farmbot.button': 'Chat with FarmBot',
    
    // Location Section
    'contact.location.title': 'Our Location',
    'contact.location.visit': 'Visit Our Office',
    'contact.location.directions': 'Get Directions',
    
    // FAQ Links
    'contact.faq.title': 'Looking for quick answers?',
    'contact.faq.aboutUs': 'About Us',
    'contact.faq.pricing': 'View Pricing',
    'contact.faq.helpCenter': 'Help Center',
    
    // Admin Contact Inquiries
    'contact.admin.title': 'Contact Inquiries',
    'contact.admin.subtitle': 'Manage and respond to contact form submissions from farmers',
    'contact.admin.total': 'Total',
    'contact.admin.new': 'New',
    'contact.admin.read': 'Read',
    'contact.admin.replied': 'Replied',
    'contact.admin.resolved': 'Resolved',
    'contact.admin.searchPlaceholder': 'Search inquiries by name, email, or subject...',
    'contact.admin.all': 'All',
    'contact.admin.noInquiries': 'No inquiries found',
    'contact.admin.unread': 'Unread',
    'contact.admin.justNow': 'Just now',
    'contact.admin.minuteAgo': '{count} minute ago',
    'contact.admin.minutesAgo': '{count} minutes ago',
    'contact.admin.hourAgo': '{count} hour ago',
    'contact.admin.hoursAgo': '{count} hours ago',
    'contact.admin.dayAgo': '{count} day ago',
    'contact.admin.daysAgo': '{count} days ago',
    'contact.admin.inquiryDetails': 'Inquiry Details',
    'contact.admin.name': 'Name',
    'contact.admin.email': 'Email',
    'contact.admin.subject': 'Subject',
    'contact.admin.message': 'Message',
    'contact.admin.status': 'Status',
    'contact.admin.submitted': 'Submitted',
    'contact.admin.repliedAt': 'Replied',
    'contact.admin.replyViaEmail': 'Reply via Email',
    'contact.admin.markRead': 'Mark Read',
    'contact.admin.markReplied': 'Mark Replied',
    'contact.admin.resolve': 'Resolve',
    'contact.admin.delete': 'Delete',
    'contact.admin.selectInquiry': 'Select an inquiry to view details',
    
    // Dashboard - Data Arrays
    // Default Crops
    'dashboard.data.wheat': 'Wheat',
    'dashboard.data.corn': 'Corn',
    'dashboard.data.rice': 'Rice',
    'dashboard.data.soybeans': 'Soybeans',
    'dashboard.data.tomato': 'Tomato',
    'dashboard.data.tomatoes': 'Tomato',
    'dashboard.data.lettuce': 'Lettuce',
    'dashboard.data.carrot': 'Carrot',
    'dashboard.data.carrots': 'Carrot',
    'dashboard.data.greenBeans': 'Green beans',
    'dashboard.data.greenbeans': 'Green beans',
    'dashboard.data.potato': 'Potato',
    'dashboard.data.potatoes': 'Potato',
    'dashboard.data.onion': 'Onion',
    'dashboard.data.onions': 'Onion',
    'dashboard.data.cucumber': 'Cucumber',
    'dashboard.data.cucumbers': 'Cucumber',
    'dashboard.data.tons': 'tons',
    
    // Alert Messages
    'dashboard.data.alertSoybeanCritical': 'Soybean stock is critically low (25%)',
    'dashboard.data.alertCornLow': 'Corn stock below 50% - consider restocking',
    'dashboard.data.alertWeather': 'Weather update: Rain expected in 3 days',
    'dashboard.data.timeHoursAgo': 'hours ago',
    'dashboard.data.timeDayAgo': 'day ago',
    'dashboard.data.timeDaysAgo': 'days ago',
    
    // Marketplace Types
    'dashboard.data.buySell': 'Buy & Sell',
    'dashboard.data.sellOnly': 'Sell Only',
    'dashboard.data.km': 'km',
    
    // Activities
    'dashboard.data.activityUpdatedWheat': 'Updated wheat stock',
    'dashboard.data.activityWheatDetail': '+500 kg added',
    'dashboard.data.activityCornHarvest': 'Corn harvested',
    'dashboard.data.activityCornDetail': '2 tons collected',
    'dashboard.data.activitySubscription': 'Subscription renewed',
    'dashboard.data.activitySubscriptionDetail': 'Pro plan extended',
    'dashboard.data.activityMarket': 'Market visit logged',
    'dashboard.data.activityMarketDetail': 'GreenMarket',
    
    // My Crops Page
    'crops.title': 'My Crops',
    'crops.subtitle': 'Manage and monitor all your crops in one place',
    'crops.allCrops': 'All Crops',
    'crops.lowStock': 'Low Stock',
    'crops.critical': 'Critical',
    'crops.viewDetails': 'View Details',
    'crops.editCrop': 'Edit Crop',
    'crops.editCropDesc': 'Update crop information and stock levels',
    'crops.deleteCrop': 'Delete Crop',
    'crops.lastUpdated': 'Last Updated',
    'crops.cropUpdated': 'Crop Updated',
    'crops.cropUpdatedDesc': 'Successfully updated',
    'crops.updateError': 'Failed to update crop',
    'crops.updating': 'Updating...',
    'crops.saveChanges': 'Save Changes',
    'crops.filterAll': 'All',
    'crops.filterGood': 'Good',
    'crops.filterLow': 'Low Stock',
    'crops.filterCritical': 'Critical',
    'crops.noCropsFound': 'No Crops Found',
    'crops.noCropsDesc': 'You haven\'t added any crops yet. Start by adding your first crop to track its stock levels.',
    'crops.noCropsFilterDesc': 'No crops match the selected filter. Try a different filter or add new crops.',
    'crops.showAllCrops': 'Show All Crops',
    
    // Notifications Page
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Stay updated with important alerts and updates',
    'notifications.markAllRead': 'Mark All as Read',
    'notifications.clearAll': 'Clear All',
    'notifications.today': 'Today',
    'notifications.yesterday': 'Yesterday',
    'notifications.older': 'Older',
    'notifications.noNotifications': 'No notifications',
    'notifications.noNotificationsDesc': 'You\'re all caught up! Check back later for new updates.',
    'notifications.stockAlert': 'Stock Alert',
    'notifications.systemUpdate': 'System Update',
    'notifications.recommendation': 'AI Recommendation',
    'notifications.criticalStock': 'has critical stock level',
    'notifications.lowStock': 'has low stock level',
    'notifications.goodStock': 'has good stock level',
    'notifications.stockStatus': 'Stock Status',
    'notifications.remaining': 'remaining',
    'notifications.justNow': 'Just now',
    'notifications.recent': 'Recently',
    'notifications.addCropsHint': 'Add crops to start receiving stock alerts',
    'notifications.refresh': 'Refresh',
    'notifications.loading': 'Loading...',
    
    // Settings Page
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences and app settings',
    'settings.accountSettings': 'Account Settings',
    'settings.notificationSettings': 'Notification Preferences',
    'settings.languageSettings': 'Language & Region',
    'settings.currentLanguage': 'Current Language',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive email alerts for important updates',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Get instant notifications on your device',
    'settings.stockAlerts': 'Stock Alerts',
    'settings.stockAlertsDesc': 'Notify me when crop stock is low',
    'settings.marketUpdates': 'Market Updates',
    'settings.marketUpdatesDesc': 'Get updates about nearby marketplaces',
    'settings.aiRecommendations': 'AI Recommendations',
    'settings.aiRecommendationsDesc': 'Receive personalized farming suggestions',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.themeLight': 'Light',
    'settings.themeDark': 'Dark',
    'settings.themeAuto': 'Auto',
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountDesc': 'Permanently delete your account and all data',
    'settings.saveChanges': 'Save Changes',
    'settings.changesSaved': 'Changes Saved',
    'settings.changesSavedDesc': 'Your settings have been updated successfully',
    
    // Explore Farms Page
    'explore.title': 'Explore Farms in Egypt',
    'explore.subtitle': 'Connect with farming communities across the country',
    'explore.clearDirections': 'Clear Directions',
    'explore.directionsCleared': 'Directions cleared',
    'explore.searchPlaceholder': 'Search farms, crops, or regions...',
    'explore.farmType': 'Farm Type',
    'explore.allTypes': 'All Types',
    'explore.organic': 'Organic',
    'explore.conventional': 'Conventional',
    'explore.mixed': 'Mixed',
    'explore.region': 'Region',
    'explore.allRegions': 'All Regions',
    'explore.delta': 'Delta',
    'explore.cairo': 'Cairo',
    'explore.alexandria': 'Alexandria',
    'explore.fayoum': 'Fayoum',
    'explore.aswan': 'Aswan',
    'explore.luxor': 'Luxor',
    'explore.featuredFarms': 'Featured Farms',
    'explore.farmers': 'farmers',
    'explore.getDirections': 'Get Directions',
    'explore.showingRoute': 'Showing Route',
    'explore.showingDirectionsTo': 'Showing directions to',
    'explore.checkMapRoute': 'Check the map for the route',
    'explore.networkStats': 'Network Stats',
    'explore.activeFarms': 'Active Farms',
    'explore.totalFarmers': 'Total Farmers',
    'explore.regionsCovered': 'Regions Covered',
    'explore.avgGrowth': 'Avg Growth',
    'explore.learnFromOthers': 'Learn from Others',
    'explore.learnFromOthersDesc': 'Connect with experienced farmers and learn best practices for your crops',
    'explore.buildNetwork': 'Build Your Network',
    'explore.buildNetworkDesc': 'Join farming communities and collaborate on shared challenges and opportunities',
    'explore.shareSuccess': 'Share Success',
    'explore.shareSuccessDesc': 'Share your farming innovations and help others improve their yields',
    'explore.noFarmsFound': 'No farms found',
    'explore.tryDifferentFilters': 'Try adjusting your search or filters',
    'explore.farmCount': 'farm',
    'explore.farmCountPlural': 'farms',
    'explore.seeAll': 'See All',
    'explore.showLess': 'Show Less',
    
    // Explore Farms Map
    'exploreFarms.mapTitle': 'Explore Farms Across Egypt',
    'exploreFarms.showingDirections': 'Showing directions to',
    'exploreFarms.hoverInfo': 'Hover over markers to see farm details and connect with farming communities',
    'exploreFarms.organic': 'Organic',
    'exploreFarms.conventional': 'Conventional',
    'exploreFarms.mixed': 'Mixed',
    'exploreFarms.farms': 'Farms',
    
    // Subscription Page
    'subscription.chooseYourPlan': 'Choose Your Plan',
    'subscription.title': 'Stay Connected to Your Crops',
    'subscription.subtitle': 'Select the perfect plan for your farming needs. All plans include a 14-day free trial.',
    'subscription.mostPopular': '⭐ Most Popular',
    'subscription.getStarted': 'Get Started',
    'subscription.securePayment': 'Secure Payment',
    'subscription.sslEncrypted': 'SSL Encrypted',
    'subscription.freeTrial': '14-Day Free Trial',
    'subscription.cancelAnytime': 'Cancel Anytime',
    'subscription.faq': 'Frequently Asked Questions',
    'subscription.faqChangePlan': 'Can I change my plan later?',
    'subscription.faqChangePlanAnswer': 'Yes! You can upgrade or downgrade your plan at any time. Changes will be reflected in your next billing cycle.',
    'subscription.faqPaymentMethods': 'What payment methods do you accept?',
    'subscription.faqPaymentMethodsAnswer': 'We accept all major credit cards (Visa, MasterCard, American Express) and PayPal.',
    'subscription.faqRefund': 'Is there a refund policy?',
    'subscription.faqRefundAnswer': 'Yes, we offer a 30-day money-back guarantee. If you\'re not satisfied, contact our support team for a full refund.',
    
    // Subscription Dashboard (My Subscription Page)
    'subscriptionDashboard.title': 'Subscription',
    'subscriptionDashboard.subtitle': 'Manage your subscription and billing information',
    'subscriptionDashboard.welcome': 'Welcome to your subscription!',
    'subscriptionDashboard.welcomeDesc': 'Your subscription is now active. Enjoy all the premium features!',
    'subscriptionDashboard.noSubscription': 'No Active Subscription',
    'subscriptionDashboard.noSubscriptionDesc': 'Subscribe to a plan to unlock all features and get AI-powered recommendations.',
    'subscriptionDashboard.viewPlans': 'View Plans',
    'subscriptionDashboard.plan': 'Plan',
    'subscriptionDashboard.subscription': 'subscription',
    'subscriptionDashboard.monthly': 'monthly',
    'subscriptionDashboard.startDate': 'Start Date',
    'subscriptionDashboard.endDate': 'End Date',
    'subscriptionDashboard.notAvailable': 'N/A',
    'subscriptionDashboard.trialActive': '14-Day Free Trial Active',
    'subscriptionDashboard.trialEnds': 'Your trial ends on {date}. You won\'t be charged until then.',
    'subscriptionDashboard.planFeatures': 'Your Plan Features',
    'subscriptionDashboard.manageSubscription': 'Manage Subscription',
    'subscriptionDashboard.changePlan': 'Change Plan',
    'subscriptionDashboard.status.active': 'Active',
    'subscriptionDashboard.status.trial': 'Trial',
    'subscriptionDashboard.status.expired': 'Expired',
    'subscriptionDashboard.status.cancelled': 'Cancelled',
    'subscriptionDashboard.feature.aiRecommendations': 'AI recommendations',
    'subscriptionDashboard.feature.unlimitedCrops': 'Unlimited crop tracking',
    'subscriptionDashboard.feature.prioritySupport': '24/7 priority support',
    'subscriptionDashboard.feature.predictiveAnalytics': 'Predictive analytics',
    'subscriptionDashboard.feature.customIntegrations': 'Custom integrations',
    'subscriptionDashboard.feature.earlyAccess': 'Early access to features',
    'subscriptionDashboard.feature.advancedAnalytics': 'Advanced analytics',
    'subscriptionDashboard.feature.weatherIntegration': 'Weather integration',
    'subscriptionDashboard.feature.marketInsights': 'Market insights',
    'subscriptionDashboard.feature.exportReports': 'Export data reports',
    'subscriptionDashboard.feature.basicNotifications': 'Basic notifications',
    'subscriptionDashboard.feature.cropTracking': 'Crop tracking (5 types)',
    'subscriptionDashboard.feature.emailSupport': 'Email support',
    'subscriptionDashboard.feature.stockMonitoring': 'Stock monitoring',
    
    // Payment Dialog
    'payment.completeSubscription': 'Complete Your Subscription',
    'payment.enterDetails': 'Enter your payment details to complete your subscription purchase.',
    'payment.plan': 'Plan',
    'payment.access': 'access',
    'payment.cardholderName': 'Cardholder Name',
    'payment.cardNumber': 'Card Number',
    'payment.expiryDate': 'Expiry Date',
    'payment.cvv': 'CVV',
    'payment.secureInfo': 'Your payment information is secure and encrypted',
    'payment.completePayment': 'Complete Payment',
    'payment.processing': 'Processing...',
    'payment.termsAgree': 'By completing this purchase, you agree to our Terms of Service and Privacy Policy. You will be charged',
    'payment.afterTrial': 'after your 14-day free trial.',
    
    // Plan Names and Descriptions
    'plan.basic.name': 'Basic',
    'plan.basic.description': 'Perfect for getting started with crop management',
    'plan.basic.duration': '1 month',
    'plan.basic.period': 'month',
    'plan.basic.feature1': '1-month access',
    'plan.basic.feature2': 'Basic notifications',
    'plan.basic.feature3': 'Crop tracking up to 5 types',
    'plan.basic.feature4': 'Email support',
    'plan.basic.feature5': 'Stock level monitoring',
    'plan.basic.feature6': 'Mobile app access',
    
    'plan.pro.name': 'Pro',
    'plan.pro.description': 'Best value for serious farmers',
    'plan.pro.duration': '6 months',
    'plan.pro.period': '6 months',
    'plan.pro.feature1': '6-month access',
    'plan.pro.feature2': 'Advanced analytics & reports',
    'plan.pro.feature3': 'Unlimited crop tracking',
    'plan.pro.feature4': 'Weather integration',
    'plan.pro.feature5': 'Priority support',
    'plan.pro.feature6': 'Market insights',
    'plan.pro.feature7': 'Export data reports',
    'plan.pro.feature8': 'Custom alerts',
    
    'plan.premium.name': 'Premium',
    'plan.premium.description': 'Ultimate package with AI-powered features',
    'plan.premium.duration': '1 year',
    'plan.premium.period': 'year',
    'plan.premium.feature1': '1-year access',
    'plan.premium.feature2': 'AI recommendations',
    'plan.premium.feature3': 'Unlimited crop tracking',
    'plan.premium.feature4': 'Advanced market insights',
    'plan.premium.feature5': 'Predictive analytics',
    'plan.premium.feature6': '24/7 priority support',
    'plan.premium.feature7': 'Dedicated account manager',
    'plan.premium.feature8': 'Custom integrations',
    'plan.premium.feature9': 'Early access to new features',
    
    // Login
    'login.welcomeBack': 'Welcome Back',
    'login.createAccount': 'Create Account',
    'login.subtitle': 'Login to manage your crops and inventory',
    'login.signupSubtitle': 'Start your 14-day free trial today',
    'login.firstName': 'First Name',
    'login.lastName': 'Last Name',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.loginButton': 'Login',
    'login.createButton': 'Create Account',
    'login.loggingIn': 'Logging in...',
    'login.creatingAccount': 'Creating Account...',
    'login.demoAccount': 'Use Demo Account',
    'login.orContinue': 'Or continue with',
    'login.google': 'Google',
    'login.facebook': 'Facebook',
    'login.haveAccount': 'Already have an account?',
    'login.noAccount': "Don't have an account?",
    'login.signup': 'Sign up',
    'login.terms': 'Terms of Service',
    'login.privacy': 'Privacy Policy',
    'login.bySigningUp': 'By signing up, you agree to our',
    'login.and': 'and',
    'login.demoInfo': 'New here? Click "Use Demo Account" below to try the app instantly!',
    'login.demoCreate': 'Or create your own account by clicking "Sign up" at the bottom.',
    'login.growSmarter': 'Grow Smarter, Not Harder',
    'login.joinThousands': 'Join thousands of farmers using AI-powered insights to maximize their harvest and streamline their operations.',
    'login.trackCrops': 'Track crops and inventory in real-time',
    'login.getAI': 'Get AI-powered recommendations',
    'login.connectMarkets': 'Connect with marketplaces instantly',
    'login.smartCropManagement': 'Smart Crop Management',
    'login.loginAs': 'Login as',
    'login.settingUpDemo': 'Setting up Demo...',
    'login.farmer': 'Farmer',
    'login.admin': 'Admin',
    'login.creatingFarmerAccount': 'Creating Farmer Account...',
    'login.creatingAdminAccount': 'Creating Admin Account...',
    'login.loggingInAsFarmer': 'Logging in as Farmer...',
    'login.loggingInAsAdmin': 'Logging in as Admin...',
    'login.createFarmerAccount': 'Create Farmer Account',
    'login.createAdminAccount': 'Create Admin Account',
    'login.loginAsFarmer': 'Login as Farmer',
    'login.loginAsAdmin': 'Login as Admin',
    
    // Contact (duplicate removed - already defined above)
    'contact.sendMessage': 'Send us a Message',
    'contact.firstName': 'First Name',
    'contact.lastName': 'Last Name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.info': 'Contact Information',
    'contact.emailLabel': 'Email',
    'contact.phone': 'Phone',
    'contact.address': 'Address',
    'contact.hours': 'Office Hours',
    'contact.needHelp': 'Need Instant Help?',
    'contact.chatBot': 'Chat with FarmBot, our AI assistant, for immediate answers to common questions.',
    'contact.chatNow': 'Chat with FarmBot',
    'contact.location': 'Our Location',
    'contact.visitOffice': 'Visit Our Office',
    'contact.directions': 'Get Directions',
    'contact.quickAnswers': 'Looking for quick answers?',
    'contact.aboutUs': 'About Us',
    'contact.viewPricing': 'View Pricing',
    'contact.helpCenter': 'Help Center',
    
    // Profile (duplicate removed - already defined above)
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.farmInfo': 'Farm Information',
    'profile.farmName': 'Farm Name',
    'profile.farmSize': 'Farm Size',
    'profile.location': 'Location',
    'profile.address': 'Full Address',
    'profile.bio': 'Bio',
    'profile.profilePicture': 'Profile Picture',
    'profile.uploadNew': 'Upload New Photo',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.settings': 'Settings',
    'common.notifications': 'Notifications',
    'common.help': 'Help',
    'common.language': 'Language',
    
    // Footer
    'footer.tagline': 'Empowering farmers with smart crop management and AI-driven insights.',
    'footer.quickLinks': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.helpCenter': 'Help Center',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.faq': 'FAQ',
    'footer.getInTouch': 'Get in Touch',
    'footer.copyright': '© 2025 Farmer Assistant. All rights reserved.',
    
    // Add Crop Dialog
    'addCrop.title': 'Add New Crop',
    'addCrop.description': 'Add a new crop to track its stock levels and manage your inventory.',
    'addCrop.cropName': 'Crop Name',
    'addCrop.cropNamePlaceholder': 'e.g., Tomato, Carrot, Rice',
    'addCrop.quantity': 'Quantity',
    'addCrop.quantityPlaceholder': '0.0',
    'addCrop.unit.tons': 'tons',
    'addCrop.unit.kg': 'kg',
    'addCrop.unit.lbs': 'lbs',
    'addCrop.unit.bushels': 'bushels',
    'addCrop.stockLevel': 'Stock Level (%)',
    'addCrop.empty': 'Empty',
    'addCrop.full': 'Full',
    'addCrop.preview': 'Preview',
    'addCrop.previewCrop': 'Crop',
    'addCrop.previewAmount': 'Amount',
    'addCrop.previewStatus': 'Status',
    'addCrop.notSpecified': 'Not specified',
    'addCrop.status.good': 'Good',
    'addCrop.status.low': 'Low',
    'addCrop.status.critical': 'Critical',
    'addCrop.cancel': 'Cancel',
    'addCrop.addButton': 'Add Crop',
    'addCrop.adding': 'Adding...',
    'addCrop.required': '*',
    'addCrop.error.missingName': 'Please enter a crop name',
    'addCrop.error.missingQuantity': 'Please enter a quantity',
    'addCrop.error.invalidQuantity': 'Please enter a valid positive number',
    'addCrop.error.invalidStock': 'Stock level must be between 0 and 100',
    'addCrop.error.duplicate': 'A crop with this name already exists',
    'addCrop.error.failed': 'Please try again',
    
    // Admin - Home Page
    'admin.home.hero.title': 'Admin Dashboard - Manage Your Farming Platform',
    'admin.home.hero.subtitle': 'Monitor farmers, track subscriptions, and analyze profits across your platform',
    'admin.home.exploreFarms': 'Explore Farms',
    'admin.home.profit': 'Profit',
    'admin.home.featured.title': 'Manage Your Farming Platform with Ease',
    'admin.home.featured.description': 'Our comprehensive admin platform provides you with powerful tools to manage farmers, track subscriptions, and analyze profits. Monitor your entire farming network from one centralized dashboard and make data-driven decisions to grow your platform.',
    'admin.home.goToDashboard': 'Go to Dashboard',
    'admin.home.features.title': 'Admin Platform Features',
    'admin.home.features.subtitle': 'Manage your farming platform with powerful admin tools',
    'admin.home.features.manageFarmers.title': 'Manage Farmers',
    'admin.home.features.manageFarmers.description': 'View all registered farmers, their subscriptions, and track their activity',
    'admin.home.features.trackProfits.title': 'Track Profits',
    'admin.home.features.trackProfits.description': 'Monitor total profits per farmer and analyze revenue across your platform',
    'admin.home.features.analytics.title': 'Analytics & Reports',
    'admin.home.features.analytics.description': 'View subscription distribution and platform-wide statistics',
    'admin.home.ai.badge': 'AI-Powered Assistant',
    'admin.home.ai.title': 'AI Chat Assistant',
    'admin.home.ai.description': 'Get instant answers and support with our AI-powered chat assistant. Ask questions about platform management, farmer analytics, subscription plans, or any other admin-related queries. The AI assistant is available 24/7 to help you make informed decisions and manage your platform efficiently.',
    'admin.home.ai.feature1.title': 'Platform Management Support',
    'admin.home.ai.feature1.description': 'Get help with managing farmers, subscriptions, and analytics',
    'admin.home.ai.feature2.title': 'Real-time Analytics Insights',
    'admin.home.ai.feature2.description': 'Understand your platform metrics and performance data',
    'admin.home.ai.feature3.title': '24/7 Available Support',
    'admin.home.ai.feature3.description': 'Access help anytime, anywhere with instant responses',
    
    // Admin - Dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.subtitle': 'Manage farmers, subscriptions, and view system statistics',
    'admin.dashboard.totalFarmers': 'Total Farmers',
    'admin.dashboard.registeredUsers': 'Registered users',
    'admin.dashboard.subscribedFarmers': 'Subscribed Farmers',
    'admin.dashboard.activeSubscriptions': 'Active subscriptions',
    'admin.dashboard.totalRevenue': 'Total Revenue',
    'admin.dashboard.fromSubscriptions': 'From subscriptions',
    'admin.dashboard.totalFarmersProfit': 'Total Farmers Profit',
    'admin.dashboard.combinedProfit': 'Combined profit',
    'admin.dashboard.subscriptionPlansDistribution': 'Subscription Plans Distribution',
    'admin.dashboard.basicPlan': 'Basic Plan',
    'admin.dashboard.proPlan': 'Pro Plan',
    'admin.dashboard.premiumPlan': 'Premium Plan',
    'admin.dashboard.farmers': 'Farmers',
    'admin.dashboard.farmersSubscriptions': 'Farmers & Subscriptions',
    'admin.dashboard.loadingFarmers': 'Loading farmers data...',
    'admin.dashboard.noFarmers': 'No farmers found',
    'admin.dashboard.totalProfit': 'Total Profit',
    'admin.dashboard.noSubscription': 'No Subscription',
    'admin.dashboard.systemNotifications': 'System Notifications',
    'admin.dashboard.systemNotificationsSubtitle': 'View system-wide notifications and alerts',
    'admin.dashboard.noSystemNotifications': 'No System Notifications',
    'admin.dashboard.noSystemNotificationsDesc': 'System notifications will appear here when there are important updates or alerts.',
    'admin.dashboard.settings.title': 'Admin Settings',
    'admin.dashboard.settings.subtitle': 'Manage system settings and preferences',
    'admin.dashboard.settings.accountSettings': 'Account Settings',
    'admin.dashboard.settings.fullName': 'Full Name',
    'admin.dashboard.settings.email': 'Email',
    'admin.dashboard.settings.role': 'Role',
    'admin.dashboard.settings.editProfile': 'Edit Profile',
    'admin.dashboard.settings.languageSettings': 'Language Settings',
    'admin.dashboard.settings.currentLanguage': 'Current Language',
    
    // Admin - Farmers Subscriptions Page
    'admin.farmers.viewAndManage': 'View and manage all farmers and their subscription details',
    'admin.farmers.subscriptionRevenue': 'Subscription Revenue',
    'admin.farmers.fromActiveSubscriptions': 'From {count} active subscriptions',
    'admin.farmers.totalCropProfit': 'Total Crop Profit',
    'admin.farmers.fromAllCropSales': 'From all farmers\' crop sales',
    'admin.farmers.totalProfitSummary': 'Total Profit Summary',
    'admin.farmers.fromActivePayments': 'From active subscription payments',
    'admin.farmers.cropProfit': 'Crop Profit',
    'admin.farmers.fromCropSales': 'From farmer crop sales',
    'admin.farmers.combinedTotal': 'Combined Total',
    'admin.farmers.revenueDescription': 'Revenue from active subscriptions - Each farmer\'s subscription price',
    'admin.farmers.totalRevenue': 'Total Revenue',
    'admin.farmers.farmer': 'Farmer',
    'admin.farmers.email': 'Email',
    'admin.farmers.subscriptionPlan': 'Subscription Plan',
    'admin.farmers.subscriptionProfit': 'Subscription Profit',
    'admin.farmers.unknown': 'Unknown',
    'admin.farmers.cropProfitDescription': 'Profit from farmer crop sales - Calculated from crop quantities and prices',
    'admin.farmers.totalCropProfitLabel': 'Total Crop Profit',
    'admin.farmers.actions': 'Actions',
    'admin.farmers.viewDetails': 'View Details',
    'admin.farmers.profitDistribution': 'Profit Distribution - {name}',
    'admin.farmers.loadingCrops': 'Loading crops...',
    'admin.farmers.totalProfitZero': 'Total Profit: 0 EGP',
    'admin.farmers.totalProfit': 'Total Profit:',
    'admin.farmers.noCropsFound': 'No crops found for this farmer',
  },
  ar: {
    // App Name
    'app.name': 'مساعد المزارع',
    
    // Navbar
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.profile': 'الملف الشخصي',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.pricing': 'الأسعار',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    
    // Home Page - Hero
    'home.hero.badge': 'ذكاء زراعي مدعوم بالذكاء الاصطناعي',
    'home.hero.title': 'تمكين المزارعين بإدارة ذكية للمحاصيل 🌱',
    'home.hero.subtitle': 'تتبع محاصيلك، أدِر مخزونك، واكتشف أفضل الأماكن لتنمية عملك.',
    'home.hero.cta': 'ابدأ التجربة المجانية',
    'home.hero.viewPlans': 'عرض خطط الاشتراك',
    
    // Home Page - How It Works
    'home.howItWorks.title': 'كيف يعمل',
    'home.howItWorks.subtitle': 'خطوات بسيطة لتحويل تجربتك الزراعية',
    'home.step1.title': 'تتبع محاصيلك',
    'home.step1.description': 'أضف محاصيلك وراقب دورة نموها بسهولة',
    'home.step2.title': 'احصل على تنبيهات ذكية',
    'home.step2.description': 'احصل على إشعارات حول المخزون المنخفض وأوقات الزراعة المثلى',
    'home.step3.title': 'اتصل بالأسواق',
    'home.step3.description': 'اكتشف الأسواق القريبة لتنمية عملك',
    
    // Home Page - AI Assistant
    'home.ai.badge': 'مساعد مدعوم بالذكاء الاصطناعي',
    'home.ai.title': 'تعرف على FarmBot - رفيقك الزراعي على مدار الساعة',
    'home.ai.description': 'اسأل FarmBot عن محاصيلك، احصل على تحديثات فورية للطقس، ابحث عن الأسواق، أو احصل على توصيات شخصية. إنه مثل وجود خبير زراعي في جيبك.',
    'home.ai.feature1.title': 'استعلامات باللغة الطبيعية',
    'home.ai.feature1.description': 'اطرح أسئلة مثل "متى يجب أن أزرع الذرة؟"',
    'home.ai.feature2.title': 'رؤى في الوقت الفعلي',
    'home.ai.feature2.description': 'احصل على تحديثات فورية للمخزون والطقس',
    'home.ai.feature3.title': 'توصيات شخصية',
    'home.ai.feature3.description': 'بناءً على موقعك والموسم',
    'home.ai.chat.greeting': 'مرحباً! كيف يمكنني مساعدتك اليوم؟ 🌱',
    'home.ai.chat.question': 'تحقق من مخزون القمح',
    'home.ai.chat.response': 'مخزون القمح الخاص بك عند 80%. لديك حوالي 2 طن متبقية. هل تريد اقتراحات للبيع؟',
    'home.ai.status': 'متصل',
    
    // Home Page - Featured Section
    'home.featured.title': 'حوّل تجربتك الزراعية',
    'home.featured.description': 'انضم إلى آلاف المزارعين الذين يستخدمون التكنولوجيا لتحسين محاصيلهم، وإدارة مخزونهم، والتواصل مع الأسواق. توفر منصتنا كل ما تحتاجه للنجاح في الزراعة الحديثة.',
    'home.featured.getStarted': 'ابدأ الآن',
    
    // Home Page - Features
    'home.features.title': 'كل ما تحتاجه للنجاح',
    'home.features.subtitle': 'ميزات قوية مصممة خصيصاً للمزارعين العصريين',
    'home.features.crop.title': 'رؤى المحاصيل',
    'home.features.crop.description': 'تتبع كل محصول مع تحليلات مفصلة وأنماط النمو',
    'home.features.weather.title': 'تكامل الطقس',
    'home.features.weather.description': 'تحديثات الطقس في الوقت الفعلي مخصصة لموقعك',
    'home.features.market.title': 'اقتراحات السوق',
    'home.features.market.description': 'ابحث عن أفضل الأماكن لشراء البذور وبيع محصولك',
    'home.features.stock.title': 'تحليلات المخزون',
    'home.features.stock.description': 'راقب مستويات المخزون واحصل على تنبيهات ذكية لإعادة التخزين',
    
    // Home Page - Subscription
    'home.subscription.title': 'اختر خطتك',
    'home.subscription.subtitle': 'ابدأ بتجربة مجانية، ثم اختر الخطة التي تناسب احتياجاتك الزراعية',
    'home.subscription.popular': 'الأكثر شعبية',
    'home.subscription.getStarted': 'ابدأ الآن',
    'home.plan.basic': 'أساسي',
    'home.plan.pro': 'احترافي',
    'home.plan.premium': 'مميز',
    'home.plan.month': 'شهر',
    'home.plan.6months': '6 أشهر',
    'home.plan.year': 'سنة',
    'home.plan.basic.feature1': 'وصول لمدة شهر واحد',
    'home.plan.basic.feature2': 'إشعارات أساسية',
    'home.plan.basic.feature3': 'تتبع المحاصيل',
    'home.plan.basic.feature4': 'دعم عبر البريد الإلكتروني',
    'home.plan.pro.feature1': 'وصول لمدة 6 أشهر',
    'home.plan.pro.feature2': 'تحليلات متقدمة',
    'home.plan.pro.feature3': 'تكامل الطقس',
    'home.plan.pro.feature4': 'دعم ذو أولوية',
    'home.plan.premium.feature1': 'وصول لمدة سنة',
    'home.plan.premium.feature2': 'توصيات الذكاء الاصطناعي',
    'home.plan.premium.feature3': 'رؤى السوق',
    'home.plan.premium.feature4': 'دعم ذو أولوية على مدار الساعة',
    
    // Home Page - CTA
    'home.cta.title': 'هل أنت مستعد لتحويل زراعتك؟',
    'home.cta.subtitle': 'انضم إلى آلاف المزارعين الذين يستخدمون بالفعل Farmer Assistant للنمو بذكاء',
    'home.cta.button': 'ابدأ تجربتك المجانية اليوم',
    
    // Dashboard
    'dashboard.welcome': 'مرحباً بعودتك',
    'dashboard.subtitle': 'إليك ما يحدث مع محاصيلك اليوم',
    'dashboard.totalCrops': 'إجمالي المحاصيل',
    'dashboard.avgStock': 'متوسط مستوى المخزون',
    'dashboard.alerts': 'التنبيهات',
    'dashboard.markets': 'الأسواق القريبة',
    'dashboard.cropOverview': 'نظرة عامة على المحاصيل',
    'dashboard.addCrop': 'إضافة محصول',
    'dashboard.profit': 'الربح',
    'dashboard.profitLocked': 'معلومات الربح مقفلة',
    'dashboard.upgradeToSeeProfit': 'قم بترقية اشتراكك لعرض حسابات الربح',
    'dashboard.aiRecommendation': 'توصية الذكاء الاصطناعي',
    'dashboard.viewDetails': 'عرض التفاصيل',
    'dashboard.dismiss': 'تجاهل',
    'dashboard.nearbyMarkets': 'الأسواق القريبة',
    'dashboard.viewMap': 'عرض الخريطة الكاملة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.upgradePremium': 'الترقية إلى بريميوم',
    'dashboard.upgradeCta': 'احصل على توصيات الذكاء الاصطناعي والدعم الأولوي',
    'dashboard.upgradeNow': 'ترقية الآن',
    'dashboard.types': 'الأنواع',
    'dashboard.active': 'نشط',
    'dashboard.found': 'موجود',
    'dashboard.within': 'في نطاق 15 كم',
    'dashboard.stockLevel': 'مستوى المخزون',
    'dashboard.good': 'جيد',
    'dashboard.low': 'منخفض',
    'dashboard.critical': 'حرج',
    'dashboard.acrossAll': 'عبر جميع المحاصيل',
    'dashboard.requiresAttention': 'يتطلب اهتماماً',
    'dashboard.allGood': 'كل شيء على ما يرام',
    'dashboard.alertCriticalStock': 'لديه مستوى مخزون حرج',
    'dashboard.alertLowStock': 'لديه مستوى مخزون منخفض',
    'dashboard.allCropsGood': 'جميع المحاصيل في حالة جيدة',
    'dashboard.activityUpdated': 'تم التحديث',
    'dashboard.noAlerts': 'لا توجد تنبيهات في الوقت الحالي',
    'dashboard.noActivities': 'لا توجد أنشطة حديثة',
    'dashboard.noCrops': 'لا توجد محاصيل بعد',
    'dashboard.noCropsDesc': 'ابدأ بتتبع محاصيلك بإضافة المحصول الأول',
    'dashboard.addFirstCrop': 'أضف محصولك الأول',
    'dashboard.myCrops': 'محاصيلي',
    'dashboard.exploreFarms': 'استكشف المزارع',
    'dashboard.subscription': 'الاشتراك',
    'dashboard.aiMessage': 'بناءً على موقعك والموسم الحالي، هذا وقت ممتاز لزراعة الذرة. ظروف الطقس مثالية، والطلب في السوق مرتفع في منطقتك.',
    'dashboard.interactiveMap': 'عرض الخريطة التفاعلية',
    'dashboard.showingMarkets': 'عرض الأسواق في نطاق 15 كم',
    'dashboard.exploreMap': 'استكشف خريطة مصر الزراعية',
    
    // Profile Page
    'profile.title': 'ملفي الشخصي',
    'profile.subtitle': 'إدارة معلوماتك الشخصية وتفاصيل المزرعة',
    'profile.loading': 'جاري تحميل الملف الشخصي...',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.saving': 'جاري الحفظ...',
    'profile.cancel': 'إلغاء',
    'profile.changePhoto': 'اضغط لتحميل صورة الملف الشخصي',
    'profile.maxSize': 'الحجم الأقصى: 5 ميجابايت',
    'profile.acres': 'فدان',
    
    // Profile Fields
    'profile.fields.fullName': 'الاسم الكامل',
    'profile.fields.email': 'البريد الإلكتروني',
    'profile.fields.phone': 'رقم الهاتف',
    'profile.fields.farmName': 'اسم المزرعة',
    'profile.fields.farmSize': 'حجم المزرعة (فدان)',
    'profile.fields.location': 'الموقع',
    'profile.fields.address': 'العنوان الكامل',
    'profile.fields.bio': 'نبذة / عن مزرعتك',
    'profile.fields.bioPlaceholder': 'أخبرنا عن خبرتك في الزراعة...',
    
    // Account Settings
    'profile.accountSettings': 'إعدادات الحساب',
    'profile.accountStatus': 'حالة الحساب',
    'profile.active': 'نشط',
    'profile.memberSince': 'عضو منذ',
    'profile.subscriptionPlan': 'خطة الاشتراك',
    'profile.proPlan': 'الخطة الاحترافية',
    'profile.twoFactor': 'المصادقة الثنائية',
    'profile.enable': 'تفعيل',
    
    // About Page
    'about.hero.title': 'حول',
    'about.hero.subtitle': 'نحن في مهمة لتمكين المزارعين في جميع أنحاء العالم بأدوات ذكية تجعل إدارة المحاصيل بسيطة وفعالة ومستدامة.',
    
    // Mission, Vision, Values
    'about.mission.title': 'مهمتنا',
    'about.mission.description': 'تمكين كل مزارع بالتكنولوجيا والرؤى التي تساعده على النمو بشكل أكثر استدامة وربحية.',
    'about.vision.title': 'رؤيتنا',
    'about.vision.description': 'عالم يتمتع فيه كل مزارع بإمكانية الوصول إلى أدوات ذكية تجعل الزراعة أسهل وأكثر كفاءة ومجزية.',
    'about.values.title': 'قيمنا',
    'about.values.description': 'الاستدامة والابتكار والتفكير في المزارع أولاً يوجه كل ما نفعله.',
    
    // Impact Section
    'about.impact.title': 'تأثيرنا',
    'about.impact.subtitle': 'مساعدة المزارعين حول العالم على تحقيق نتائج أفضل',
    'about.impact.activeFarmers': 'مزارع نشط',
    'about.impact.hectaresManaged': 'هكتار مدار',
    'about.impact.yieldIncrease': 'متوسط زيادة الإنتاج',
    'about.impact.wasteReduction': 'تقليل الفاقد',
    
    // Team Section
    'about.team.title': 'تعرف على فريقنا',
    'about.team.subtitle': 'مجموعة متحمسة من الخبراء المكرسين لتحويل الزراعة',
    'about.team.member1.name': 'سارة جونسون',
    'about.team.member1.role': 'المؤسس والرئيس التنفيذي',
    'about.team.member1.bio': 'مهندسة زراعية ولديها 15 عاماً من الخبرة في الزراعة',
    'about.team.member2.name': 'مايكل تشين',
    'about.team.member2.role': 'رئيس الذكاء الاصطناعي',
    'about.team.member2.bio': 'متخصص في الذكاء الاصطناعي يركز على تكنولوجيا الزراعة المستدامة',
    'about.team.member3.name': 'إميلي رودريغيز',
    'about.team.member3.role': 'قائد المنتج',
    'about.team.member3.bio': 'شغوفة بإنشاء أدوات تمكن المزارعين',
    'about.team.member4.name': 'ديفيد كومار',
    'about.team.member4.role': 'رئيس الدعم',
    'about.team.member4.bio': 'مكرس لمساعدة المزارعين على النجاح مع منصتنا',
    
    // Sustainability Section
    'about.sustainability.title': 'ملتزمون بالاستدامة',
    'about.sustainability.description': 'نحن نؤمن بأن التكنولوجيا والاستدامة يسيران جنباً إلى جنب. تساعد منصتنا المزارعين على تقليل الفاقد، وتحسين استخدام الموارد، وتطبيق ممارسات زراعية أكثر صديقة للبيئة.',
    'about.sustainability.chemical.title': 'تقليل استخدام المواد الكيميائية',
    'about.sustainability.chemical.description': 'التنبيهات الذكية تساعد المزارعين على تطبيق الأسمدة والمبيدات الحشرية فقط عند الحاجة',
    'about.sustainability.waste.title': 'تقليل هدر الطعام',
    'about.sustainability.waste.description': 'تتبع أفضل للمخزون واتصالات السوق تقلل من خسائر ما بعد الحصاد',
    'about.sustainability.resources.title': 'تحسين استخدام الموارد',
    'about.sustainability.resources.description': 'رؤى مبنية على البيانات تساعد المزارعين على استخدام المياه والطاقة بكفاءة أكبر',
    
    // Story Section
    'about.story.title': 'قصتنا',
    'about.story.paragraph1': 'ولدت من ملاحظة بسيطة: يعمل المزارعون بجد كبير، ومع ذلك يفتقر الكثيرون إلى الوصول إلى الأدوات الرقمية التي يمكن أن تجعل حياتهم أسهل وأعمالهم أكثر ربحية.',
    'about.story.paragraph2': 'مؤسستنا، سارة جونسون، نشأت في مزرعة عائلية وشهدت بشكل مباشر التحديات التي يواجهها المزارعون يومياً. بعد دراسة الهندسة الزراعية والعمل في صناعة التكنولوجيا، أدركت أن هناك فجوة بين التكنولوجيا المتطورة ومجتمع الزراعة.',
    'about.story.paragraph3.start': 'اليوم،',
    'about.story.paragraph3.end': 'تخدم الآلاف من المزارعين في جميع أنحاء العالم، وتزودهم برؤى مدعومة بالذكاء الاصطناعي ومراقبة في الوقت الفعلي واتصالات السوق التي تساعدهم على النجاح في صناعة تنافسية بشكل متزايد. نحن في البداية فقط، ونحن ملتزمون بتحسين منصتنا بشكل مستمر بناءً على ملاحظات المزارعين.',
    
    // Contact Page
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'هل لديك سؤال أو تحتاج إلى دعم؟ نحن هنا لمساعدتك على النجاح.',
    
    // Contact Form
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.firstName': 'الاسم الأول',
    'contact.form.lastName': 'اسم العائلة',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.subject': 'الموضوع',
    'contact.form.message': 'الرسالة',
    'contact.form.firstNamePlaceholder': 'أحمد',
    'contact.form.lastNamePlaceholder': 'المزارع',
    'contact.form.emailPlaceholder': 'ahmed@farm.com',
    'contact.form.subjectPlaceholder': 'كيف يمكننا مساعدتك؟',
    'contact.form.messagePlaceholder': 'أخبرنا المزيد عن استفسارك...',
    'contact.form.sendButton': 'إرسال الرسالة',
    
    // Contact Information
    'contact.info.title': 'معلومات الاتصال',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.phone': 'الهاتف',
    'contact.info.address': 'العنوان',
    'contact.info.addressLine1': 'شارع الزراعة 123',
    'contact.info.addressLine2': 'فارمفيل، كاليفورنيا 94016',
    
    // Office Hours
    'contact.hours.title': 'ساعات العمل',
    'contact.hours.mondayFriday': 'الإثنين - الجمعة',
    'contact.hours.mondayFridayTime': '9:00 صباحاً - 6:00 مساءً',
    'contact.hours.saturday': 'السبت',
    'contact.hours.saturdayTime': '10:00 صباحاً - 4:00 مساءً',
    'contact.hours.sunday': 'الأحد',
    'contact.hours.sundayTime': 'مغلق',
    
    // FarmBot CTA
    'contact.farmbot.title': 'تحتاج إلى مساعدة فورية؟',
    'contact.farmbot.description': 'تحدث مع FarmBot، مساعدنا بالذكاء الاصطناعي، للحصول على إجابات فورية للأسئلة الشائعة.',
    'contact.farmbot.button': 'تحدث مع FarmBot',
    
    // Location Section
    'contact.location.title': 'موقعنا',
    'contact.location.visit': 'زر مكتبنا',
    'contact.location.directions': 'احصل على الاتجاهات',
    
    // FAQ Links
    'contact.faq.title': 'تبحث عن إجابات سريعة؟',
    'contact.faq.aboutUs': 'من نحن',
    'contact.faq.pricing': 'عرض الأسعار',
    'contact.faq.helpCenter': 'مركز المساعدة',
    
    // Admin Contact Inquiries
    'contact.admin.title': 'استفسارات الاتصال',
    'contact.admin.subtitle': 'إدارة والرد على استمارات الاتصال من المزارعين',
    'contact.admin.total': 'الإجمالي',
    'contact.admin.new': 'جديد',
    'contact.admin.read': 'مقروء',
    'contact.admin.replied': 'تم الرد',
    'contact.admin.resolved': 'تم الحل',
    'contact.admin.searchPlaceholder': 'ابحث في الاستفسارات بالاسم أو البريد الإلكتروني أو الموضوع...',
    'contact.admin.all': 'الكل',
    'contact.admin.noInquiries': 'لم يتم العثور على استفسارات',
    'contact.admin.unread': 'غير مقروء',
    'contact.admin.justNow': 'الآن',
    'contact.admin.minuteAgo': 'منذ {count} دقيقة',
    'contact.admin.minutesAgo': 'منذ {count} دقيقة',
    'contact.admin.hourAgo': 'منذ {count} ساعة',
    'contact.admin.hoursAgo': 'منذ {count} ساعة',
    'contact.admin.dayAgo': 'منذ {count} يوم',
    'contact.admin.daysAgo': 'منذ {count} يوم',
    'contact.admin.inquiryDetails': 'تفاصيل الاستفسار',
    'contact.admin.name': 'الاسم',
    'contact.admin.email': 'البريد الإلكتروني',
    'contact.admin.subject': 'الموضوع',
    'contact.admin.message': 'الرسالة',
    'contact.admin.status': 'الحالة',
    'contact.admin.submitted': 'تم الإرسال',
    'contact.admin.repliedAt': 'تم الرد',
    'contact.admin.replyViaEmail': 'الرد عبر البريد الإلكتروني',
    'contact.admin.markRead': 'تعليم كمقروء',
    'contact.admin.markReplied': 'تعليم كتم الرد',
    'contact.admin.resolve': 'حل',
    'contact.admin.delete': 'حذف',
    'contact.admin.selectInquiry': 'اختر استفساراً لعرض التفاصيل',
    
    // Dashboard - Data Arrays
    // Default Crops
    'dashboard.data.wheat': 'القمح',
    'dashboard.data.corn': 'الذرة',
    'dashboard.data.rice': 'الأرز',
    'dashboard.data.soybeans': 'فول الصويا',
    'dashboard.data.tomato': 'الطماطم',
    'dashboard.data.tomatoes': 'الطماطم',
    'dashboard.data.lettuce': 'الخس',
    'dashboard.data.carrot': 'الجزر',
    'dashboard.data.carrots': 'الجزر',
    'dashboard.data.greenBeans': 'الفاصوليا الخضراء',
    'dashboard.data.greenbeans': 'الفاصوليا الخضراء',
    'dashboard.data.potato': 'البطاطس',
    'dashboard.data.potatoes': 'البطاطس',
    'dashboard.data.onion': 'البصل',
    'dashboard.data.onions': 'البصل',
    'dashboard.data.cucumber': 'الخيار',
    'dashboard.data.cucumbers': 'الخيار',
    'dashboard.data.tons': 'طن',
    
    // Alert Messages
    'dashboard.data.alertSoybeanCritical': 'مخزون فول الصويا منخفض بشكل حرج (25%)',
    'dashboard.data.alertCornLow': 'مخزون الذرة أقل من 50% - يُنصح بإعادة التخزين',
    'dashboard.data.alertWeather': 'تحديث الطقس: من المتوقع هطول أمطار خلال 3 أيام',
    'dashboard.data.timeHoursAgo': 'منذ ساعات',
    'dashboard.data.timeDayAgo': 'منذ يوم',
    'dashboard.data.timeDaysAgo': 'منذ أيام',
    
    // Marketplace Types
    'dashboard.data.buySell': 'شراء وبيع',
    'dashboard.data.sellOnly': 'بيع فقط',
    'dashboard.data.km': 'كم',
    
    // Activities
    'dashboard.data.activityUpdatedWheat': 'تحديث مخزون القمح',
    'dashboard.data.activityWheatDetail': 'إضافة +500 كجم',
    'dashboard.data.activityCornHarvest': 'حصاد الذرة',
    'dashboard.data.activityCornDetail': 'تم جمع 2 طن',
    'dashboard.data.activitySubscription': 'تجديد الاشتراك',
    'dashboard.data.activitySubscriptionDetail': 'تمديد الخطة الاحترافية',
    'dashboard.data.activityMarket': 'تسجيل زيارة السوق',
    'dashboard.data.activityMarketDetail': 'GreenMarket',
    
    // My Crops Page
    'crops.title': 'محاصيلي',
    'crops.subtitle': 'إدارة ومراقبة جميع محاصيلك في مكان واحد',
    'crops.allCrops': 'جميع المحاصيل',
    'crops.lowStock': 'مخزون منخفض',
    'crops.critical': 'حرج',
    'crops.viewDetails': 'عرض التفاصيل',
    'crops.editCrop': 'تعديل المحصول',
    'crops.editCropDesc': 'تحديث معلومات المحصول ومستويات المخزون',
    'crops.deleteCrop': 'حذف المحصول',
    'crops.lastUpdated': 'آخر تحديث',
    'crops.cropUpdated': 'تم تحديث المحصول',
    'crops.cropUpdatedDesc': 'تم التحديث بنجاح',
    'crops.updateError': 'فشل تحديث المحصول',
    'crops.updating': 'جاري التحديث...',
    'crops.saveChanges': 'حفظ التغييرات',
    'crops.filterAll': 'الكل',
    'crops.filterGood': 'جيد',
    'crops.filterLow': 'مخزون منخفض',
    'crops.filterCritical': 'حرج',
    'crops.noCropsFound': 'لم يتم العثور على محاصيل',
    'crops.noCropsDesc': 'لم تقم بإضافة أي محاصيل بعد. ابدأ بإضافة أول محصول لتتبع مستويات المخزون.',
    'crops.noCropsFilterDesc': 'لا توجد محاصيل تطابق الفلتر المحدد. جرب فلتراً مختلفاً أو أضف محاصيل جديدة.',
    'crops.showAllCrops': 'عرض جميع المحاصيل',
    
    // Notifications Page
    'notifications.title': 'الإشعارات',
    'notifications.subtitle': 'ابق على اطلاع بالتنبيهات والتحديثات المهمة',
    'notifications.markAllRead': 'تعليم الكل كمقروء',
    'notifications.clearAll': 'مسح الكل',
    'notifications.today': 'اليوم',
    'notifications.yesterday': 'أمس',
    'notifications.older': 'الأقدم',
    'notifications.noNotifications': 'لا توجد إشعارات',
    'notifications.noNotificationsDesc': 'أنت على اطلاع بكل شيء! تحقق لاحقاً للحصول على تحديثات جديدة.',
    'notifications.stockAlert': 'تنبيه المخزون',
    'notifications.systemUpdate': 'تحديث النظام',
    'notifications.recommendation': 'توصية الذكاء الاصطناعي',
    'notifications.criticalStock': 'لديه مستوى مخزون حرج',
    'notifications.lowStock': 'لديه مستوى مخزون منخفض',
    'notifications.goodStock': 'لديه مستوى مخزون جيد',
    'notifications.stockStatus': 'حالة المخزون',
    'notifications.remaining': 'متبقي',
    'notifications.justNow': 'الآن',
    'notifications.recent': 'مؤخراً',
    'notifications.addCropsHint': 'أضف محاصيل لبدء تلقي تنبيهات المخزون',
    'notifications.refresh': 'تحديث',
    'notifications.loading': 'جاري التحميل...',
    
    // Settings Page
    'settings.title': 'الإعدادات',
    'settings.subtitle': 'إدارة تفضيلات حسابك وإعدادات التطبيق',
    'settings.accountSettings': 'إعدادات الحساب',
    'settings.notificationSettings': 'تفضيلات الإشعارات',
    'settings.languageSettings': 'اللغة والمنطقة',
    'settings.currentLanguage': 'اللغة الحالية',
    'settings.emailNotifications': 'إشعارات البريد الإلكتروني',
    'settings.emailNotificationsDesc': 'تلقي تنبيهات البريد الإلكتروني للتحديثات المهمة',
    'settings.pushNotifications': 'الإشعارات الفورية',
    'settings.pushNotificationsDesc': 'احصل على إشعارات فورية على جهازك',
    'settings.stockAlerts': 'تنبيهات المخزون',
    'settings.stockAlertsDesc': 'أبلغني عندما يكون مخزون المحصول منخفضاً',
    'settings.marketUpdates': 'تحديثات السوق',
    'settings.marketUpdatesDesc': 'احصل على تحديثات حول الأسواق القريبة',
    'settings.aiRecommendations': 'توصيات الذكاء الاصطناعي',
    'settings.aiRecommendationsDesc': 'تلقي اقتراحات زراعية مخصصة',
    'settings.appearance': 'المظهر',
    'settings.theme': 'السمة',
    'settings.themeLight': 'فاتح',
    'settings.themeDark': 'داكن',
    'settings.themeAuto': 'تلقائي',
    'settings.dangerZone': 'منطقة الخطر',
    'settings.deleteAccount': 'حذف الحساب',
    'settings.deleteAccountDesc': 'حذف حسابك وجميع البيانات نهائياً',
    'settings.saveChanges': 'حفظ التغييرات',
    'settings.changesSaved': 'تم حفظ التغييرات',
    'settings.changesSavedDesc': 'تم تحديث إعداداتك بنجاح',
    
    // Explore Farms Page
    'explore.title': 'استكشف المزارع في مصر',
    'explore.subtitle': 'تواصل مع مجتمعات الزراعة في جميع أنحاء البلاد',
    'explore.clearDirections': 'مسح الاتجاهات',
    'explore.directionsCleared': 'تم مسح الاتجاهات',
    'explore.searchPlaceholder': 'ابحث عن المزارع أو المحاصيل أو المناطق...',
    'explore.farmType': 'نوع المزرعة',
    'explore.allTypes': 'جميع الأنواع',
    'explore.organic': 'عضوي',
    'explore.conventional': 'تقليدي',
    'explore.mixed': 'مختلط',
    'explore.region': 'المنطقة',
    'explore.allRegions': 'جميع المناطق',
    'explore.delta': 'الدلتا',
    'explore.cairo': 'القاهرة',
    'explore.alexandria': 'الإسكندرية',
    'explore.fayoum': 'الفيوم',
    'explore.aswan': 'أسوان',
    'explore.luxor': 'الأقصر',
    'explore.featuredFarms': 'المزارع المميزة',
    'explore.farmers': 'مزارعون',
    'explore.getDirections': 'احصل على الاتجاهات',
    'explore.showingRoute': 'عرض المسار',
    'explore.showingDirectionsTo': 'عرض الاتجاهات إلى',
    'explore.checkMapRoute': 'تحقق من الخريطة للحصول على المسار',
    'explore.networkStats': 'إحصائيات الشبكة',
    'explore.activeFarms': 'المزارع النشطة',
    'explore.totalFarmers': 'إجمالي المزارعين',
    'explore.regionsCovered': 'المناطق المشمولة',
    'explore.avgGrowth': 'متوسط النمو',
    'explore.learnFromOthers': 'تعلم من الآخرين',
    'explore.learnFromOthersDesc': 'تواصل مع المزارعين ذوي الخبرة وتعلم أفضل الممارسات لمحاصيلك',
    'explore.buildNetwork': 'بناء شبكتك',
    'explore.buildNetworkDesc': 'انضم إلى مجتمعات الزراعة وتعاون في التحديات والفرص المشتركة',
    'explore.shareSuccess': 'مشاركة النجاح',
    'explore.shareSuccessDesc': 'شارك ابتكاراتك الزراعية وساعد الآخرين على تحسين محاصيلهم',
    'explore.noFarmsFound': 'لم يتم العثور على مزارع',
    'explore.tryDifferentFilters': 'حاول تعديل البحث أو المرشحات',
    'explore.farmCount': 'مزرعة',
    'explore.farmCountPlural': 'مزارع',
    'explore.seeAll': 'عرض الكل',
    'explore.showLess': 'عرض أقل',
    
    // Explore Farms Map
    'exploreFarms.mapTitle': 'استكشف المزارع في مصر',
    'exploreFarms.showingDirections': 'عرض الاتجاهات إلى',
    'exploreFarms.hoverInfo': 'مرر الماوس فوق العلامات لرؤية تفاصيل المزرعة والتواصل مع مجتمعات الزراعة',
    'exploreFarms.organic': 'عضوي',
    'exploreFarms.conventional': 'تقليدي',
    'exploreFarms.mixed': 'مختلط',
    'exploreFarms.farms': 'مزارع',
    
    // Subscription Page
    'subscription.chooseYourPlan': 'اختر خطتك',
    'subscription.title': 'ابق على اتصال بمحاصيلك',
    'subscription.subtitle': 'اختر الخطة المثالية لاحتياجاتك الزراعية. جميع الخطط تشمل تجربة مجانية لمدة 14 يوماً.',
    'subscription.mostPopular': '⭐ الأكثر شعبية',
    'subscription.getStarted': 'ابدأ الآن',
    'subscription.securePayment': 'دفع آمن',
    'subscription.sslEncrypted': 'مشفر بـ SSL',
    'subscription.freeTrial': 'تجربة مجانية لمدة 14 يوماً',
    'subscription.cancelAnytime': 'إلغاء في أي وقت',
    'subscription.faq': 'الأسئلة الشائعة',
    'subscription.faqChangePlan': 'هل يمكنني تغيير خطتي لاحقاً؟',
    'subscription.faqChangePlanAnswer': 'نعم! يمكنك الترقية أو التخفيض في أي وقت. ستنعكس التغييرات في دورة الفوترة التالية.',
    'subscription.faqPaymentMethods': 'ما هي طرق الدفع المقبولة؟',
    'subscription.faqPaymentMethodsAnswer': 'نقبل جميع بطاقات الائتمان الرئيسية (فيزا، ماستر كارد، أمريكان إكسبريس) وPayPal.',
    'subscription.faqRefund': 'هل هناك سياسة استرداد؟',
    'subscription.faqRefundAnswer': 'نعم، نقدم ضمان استرداد الأموال لمدة 30 يوماً. إذا لم تكن راضياً، اتصل بفريق الدعم للحصول على استرداد كامل.',
    
    // Subscription Dashboard (My Subscription Page)
    'subscriptionDashboard.title': 'الاشتراك',
    'subscriptionDashboard.subtitle': 'إدارة اشتراكك ومعلومات الفوترة',
    'subscriptionDashboard.welcome': 'مرحباً بك في اشتراكك!',
    'subscriptionDashboard.welcomeDesc': 'اشتراكك نشط الآن. استمتع بجميع الميزات المميزة!',
    'subscriptionDashboard.noSubscription': 'لا يوجد اشتراك نشط',
    'subscriptionDashboard.noSubscriptionDesc': 'اشترك في خطة لفتح جميع الميزات والحصول على توصيات مدعومة بالذكاء الاصطناعي.',
    'subscriptionDashboard.viewPlans': 'عرض الخطط',
    'subscriptionDashboard.plan': 'خطة',
    'subscriptionDashboard.subscription': 'اشتراك',
    'subscriptionDashboard.monthly': 'شهري',
    'subscriptionDashboard.startDate': 'تاريخ البدء',
    'subscriptionDashboard.endDate': 'تاريخ الانتهاء',
    'subscriptionDashboard.notAvailable': 'غير متاح',
    'subscriptionDashboard.trialActive': 'تجربة مجانية لمدة 14 يوماً نشطة',
    'subscriptionDashboard.trialEnds': 'تنتهي تجربتك في {date}. لن يتم محاسبتك حتى ذلك الحين.',
    'subscriptionDashboard.planFeatures': 'ميزات خطتك',
    'subscriptionDashboard.manageSubscription': 'إدارة الاشتراك',
    'subscriptionDashboard.changePlan': 'تغيير الخطة',
    'subscriptionDashboard.status.active': 'نشط',
    'subscriptionDashboard.status.trial': 'تجريبي',
    'subscriptionDashboard.status.expired': 'منتهي',
    'subscriptionDashboard.status.cancelled': 'ملغي',
    'subscriptionDashboard.feature.aiRecommendations': 'توصيات الذكاء الاصطناعي',
    'subscriptionDashboard.feature.unlimitedCrops': 'تتبع محاصيل غير محدود',
    'subscriptionDashboard.feature.prioritySupport': 'دعم ذو أولوية على مدار الساعة',
    'subscriptionDashboard.feature.predictiveAnalytics': 'تحليلات تنبؤية',
    'subscriptionDashboard.feature.customIntegrations': 'تكاملات مخصصة',
    'subscriptionDashboard.feature.earlyAccess': 'وصول مبكر إلى الميزات',
    'subscriptionDashboard.feature.advancedAnalytics': 'تحليلات متقدمة',
    'subscriptionDashboard.feature.weatherIntegration': 'تكامل الطقس',
    'subscriptionDashboard.feature.marketInsights': 'رؤى السوق',
    'subscriptionDashboard.feature.exportReports': 'تصدير تقارير البيانات',
    'subscriptionDashboard.feature.basicNotifications': 'إشعارات أساسية',
    'subscriptionDashboard.feature.cropTracking': 'تتبع المحاصيل (5 أنواع)',
    'subscriptionDashboard.feature.emailSupport': 'دعم عبر البريد الإلكتروني',
    'subscriptionDashboard.feature.stockMonitoring': 'مراقبة المخزون',
    
    // Payment Dialog
    'payment.completeSubscription': 'أكمل اشتراكك',
    'payment.enterDetails': 'أدخل تفاصيل الدفع لإكمال شراء اشتراكك.',
    'payment.plan': 'خطة',
    'payment.access': 'وصول',
    'payment.cardholderName': 'اسم حامل البطاقة',
    'payment.cardNumber': 'رقم البطاق��',
    'payment.expiryDate': 'تاريخ الانتهاء',
    'payment.cvv': 'رمز الأمان',
    'payment.secureInfo': 'معلومات الدفع الخاصة بك آمنة ومشفرة',
    'payment.completePayment': 'إتمام الدفع',
    'payment.processing': 'جاري المعالجة...',
    'payment.termsAgree': 'بإكمال هذا الشراء، فإنك توافق على شروط الخدمة وسياسة الخصوصية. سيتم محاسبتك',
    'payment.afterTrial': 'بعد تجربتك المجانية لمدة 14 يوماً.',
    
    // Plan Names and Descriptions
    'plan.basic.name': 'أساسي',
    'plan.basic.description': 'مثالي للبدء في إدارة المحاصيل',
    'plan.basic.duration': 'شهر واحد',
    'plan.basic.period': 'شهر',
    'plan.basic.feature1': 'وصول لمدة شهر واحد',
    'plan.basic.feature2': 'إشعارات أساسية',
    'plan.basic.feature3': 'تتبع المحاصيل حتى 5 أنواع',
    'plan.basic.feature4': 'دعم عبر البريد الإلكتروني',
    'plan.basic.feature5': 'مراقبة مستوى المخزون',
    'plan.basic.feature6': 'وصول إلى تطبيق الجوال',
    
    'plan.pro.name': 'احترافي',
    'plan.pro.description': 'أفضل قيمة للمزارعين الجادين',
    'plan.pro.duration': '6 أشهر',
    'plan.pro.period': '6 أشهر',
    'plan.pro.feature1': 'وصول لمدة 6 أشهر',
    'plan.pro.feature2': 'تحليلات وتقارير متقدمة',
    'plan.pro.feature3': 'تتبع محاصيل غير محدود',
    'plan.pro.feature4': 'تكامل الطقس',
    'plan.pro.feature5': 'دعم ذو أولوية',
    'plan.pro.feature6': 'رؤى السوق',
    'plan.pro.feature7': 'تصدير تقارير البيانات',
    'plan.pro.feature8': 'تنبيهات مخصصة',
    
    'plan.premium.name': 'مميز',
    'plan.premium.description': 'الباقة المثلى مع ميزات مدعومة بالذكاء الاصطناعي',
    'plan.premium.duration': 'سنة واحدة',
    'plan.premium.period': 'سنة',
    'plan.premium.feature1': 'وصول لمدة سنة واحدة',
    'plan.premium.feature2': 'توصيات الذكاء الاصطناعي',
    'plan.premium.feature3': 'تتبع محاصيل غير محدود',
    'plan.premium.feature4': 'رؤى سوق متقدمة',
    'plan.premium.feature5': 'تحليلات تنبؤية',
    'plan.premium.feature6': 'دعم ذو أولوية على مدار الساعة',
    'plan.premium.feature7': 'مدير حساب مخصص',
    'plan.premium.feature8': 'تكاملات مخصصة',
    'plan.premium.feature9': 'وصول مبكر إلى الميزات الجديدة',
    
    // Dashboard (duplicate removed - already defined above)
    
    // Login
    'login.welcomeBack': 'مرحباً بعودتك',
    'login.createAccount': 'إنشاء حساب',
    'login.subtitle': 'تسجيل الدخول لإدارة محاصيلك ومخزونك',
    'login.signupSubtitle': 'ابدأ تجربتك المجانية لمدة 14 يوماً اليوم',
    'login.firstName': 'الاسم الأول',
    'login.lastName': 'اسم العائلة',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.rememberMe': 'تذكرني',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.loginButton': 'تسجيل الدخول',
    'login.createButton': 'إنشاء حساب',
    'login.loggingIn': 'جاري تسجيل الدخول...',
    'login.creatingAccount': 'جاري إنشاء الحساب...',
    'login.demoAccount': 'استخدام حساب تجريبي',
    'login.orContinue': 'أو تابع مع',
    'login.google': 'جوجل',
    'login.facebook': 'فيسبوك',
    'login.haveAccount': 'لديك حساب بالفعل؟',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.signup': 'سجل',
    'login.terms': 'شروط الخدمة',
    'login.privacy': 'سياسة الخصوصية',
    'login.bySigningUp': 'بالتسجيل، أنت توافق على',
    'login.and': 'و',
    'login.demoInfo': 'جديد هنا؟ انقر على "استخدام حساب تجريبي" أدناه لتجربة التطبيق فوراً!',
    'login.demoCreate': 'أو أنشئ حسابك الخاص بالنقر على "سجل" في الأسفل.',
    'login.growSmarter': 'ازرع بذكاء، وليس بجهد',
    'login.joinThousands': 'انضم إلى آلاف المزارعين الذين يستخدمون رؤى الذكاء الاصطناعي لتعظيم محصولهم وتبسيط عملياتهم.',
    'login.trackCrops': 'تتبع المحاصيل والمخزون في الوقت الفعلي',
    'login.getAI': 'احصل على توصيات مدعومة بالذكاء الاصطناعي',
    'login.connectMarkets': 'اتصل بالأسواق على الفور',
    'login.smartCropManagement': 'إدارة ذكية للمحاصيل',
    'login.loginAs': 'تسجيل الدخول كـ',
    'login.settingUpDemo': 'جاري إعداد الحساب التجريبي...',
    'login.farmer': 'مزارع',
    'login.admin': 'مدير',
    'login.creatingFarmerAccount': 'جاري إنشاء حساب مزارع...',
    'login.creatingAdminAccount': 'جاري إنشاء حساب مدير...',
    'login.loggingInAsFarmer': 'جاري تسجيل الدخول كـ مزارع...',
    'login.loggingInAsAdmin': 'جاري تسجيل الدخول كـ مدير...',
    'login.createFarmerAccount': 'إنشاء حساب مزارع',
    'login.createAdminAccount': 'إنشاء حساب مدير',
    'login.loginAsFarmer': 'تسجيل الدخول كـ مزارع',
    'login.loginAsAdmin': 'تسجيل الدخول كـ مدير',
    
    // Contact (duplicate removed - already defined above)
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.firstName': 'الاسم الأول',
    'contact.lastName': 'اسم العائلة',
    'contact.email': 'البريد الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'contact.info': 'معلومات الاتصال',
    'contact.emailLabel': 'البريد الإلكتروني',
    'contact.phone': 'الهاتف',
    'contact.address': 'العنوان',
    'contact.hours': 'ساعات العمل',
    'contact.needHelp': 'تحتاج مساعدة فورية؟',
    'contact.chatBot': 'تحدث مع FarmBot، مساعدنا الذكي، للحصول على إجابات فورية للأسئلة الشائعة.',
    'contact.chatNow': 'تحدث مع FarmBot',
    'contact.location': 'موقعنا',
    'contact.visitOffice': 'قم بزيارة مكتبنا',
    'contact.directions': 'احصل على الاتجاهات',
    'contact.quickAnswers': 'تبحث عن إجابات سريعة؟',
    'contact.aboutUs': 'من نحن',
    'contact.viewPricing': 'عرض الأسعار',
    'contact.helpCenter': 'مركز المساعدة',
    
    // Profile (duplicate removed - already defined above)
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.fullName': 'الاسم الكامل',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'رقم الهاتف',
    'profile.farmInfo': 'معلومات المزرعة',
    'profile.farmName': 'اسم المزرعة',
    'profile.farmSize': 'حجم المزرعة',
    'profile.location': 'الموقع',
    'profile.address': 'العنوان الكامل',
    'profile.bio': 'نبذة',
    'profile.profilePicture': 'صورة الملف الشخصي',
    'profile.uploadNew': 'تحميل صورة جديدة',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.close': 'إغلاق',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.refresh': 'تحديث',
    'common.settings': 'الإعدادات',
    'common.notifications': 'الإشعارات',
    'common.help': 'مساعدة',
    'common.language': 'اللغة',
    
    // Footer
    'footer.tagline': 'تمكين المزارعين بإدارة ذكية للمحاصيل ورؤى مدعومة بالذكاء الاصطناعي.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.resources': 'الموارد',
    'footer.helpCenter': 'مركز المساعدة',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.getInTouch': 'تواصل معنا',
    'footer.copyright': '© 2025 مساعد المزارع. جميع الحقوق محفوظة.',
    
    // Add Crop Dialog
    'addCrop.title': 'إضافة محصول جديد',
    'addCrop.description': 'أضف محصولاً جديداً لتتبع مستويات المخزون وإدارة مخزونك.',
    'addCrop.cropName': 'اسم المحصول',
    'addCrop.cropNamePlaceholder': 'مثال: الطماطم، الجزر، الأرز',
    'addCrop.quantity': 'الكمية',
    'addCrop.quantityPlaceholder': '0.0',
    'addCrop.unit.tons': 'طن',
    'addCrop.unit.kg': 'كجم',
    'addCrop.unit.lbs': 'رطل',
    'addCrop.unit.bushels': 'بوشل',
    'addCrop.stockLevel': 'مستوى المخزون (%)',
    'addCrop.empty': 'فارغ',
    'addCrop.full': 'ممتلئ',
    'addCrop.preview': 'معاينة',
    'addCrop.previewCrop': 'المحصول',
    'addCrop.previewAmount': 'الكمية',
    'addCrop.previewStatus': 'الحالة',
    'addCrop.notSpecified': 'غير محدد',
    'addCrop.status.good': 'جيد',
    'addCrop.status.low': 'منخفض',
    'addCrop.status.critical': 'حرج',
    'addCrop.cancel': 'إلغاء',
    'addCrop.addButton': 'إضافة محصول',
    'addCrop.adding': 'جاري الإضافة...',
    'addCrop.required': '*',
    'addCrop.error.missingName': 'الرجاء إدخال اسم المحصول',
    'addCrop.error.missingQuantity': 'الرجاء إدخال الكمية',
    'addCrop.error.invalidQuantity': 'الرجاء إدخال رقم موجب صالح',
    'addCrop.error.invalidStock': 'يجب أن يكون مستوى المخزون بين 0 و 100',
    'addCrop.error.duplicate': 'يوجد محصول بهذا الاسم بالفعل',
    'addCrop.error.failed': 'الرجاء المحاولة مرة أخرى',
    
    // Admin - Home Page
    'admin.home.hero.title': 'لوحة تحكم المدير - إدارة منصة الزراعة الخاصة بك',
    'admin.home.hero.subtitle': 'راقب المزارعين، تتبع الاشتراكات، وحلل الأرباح عبر منصتك',
    'admin.home.exploreFarms': 'استكشف المزارع',
    'admin.home.profit': 'الربح',
    'admin.home.featured.title': 'إدارة منصة الزراعة الخاصة بك بسهولة',
    'admin.home.featured.description': 'توفر منصة المدير الشاملة لدينا أدوات قوية لإدارة المزارعين، وتتبع الاشتراكات، وتحليل الأرباح. راقب شبكة الزراعة بأكملها من لوحة تحكم مركزية واحدة واتخذ قرارات مدعومة بالبيانات لتنمية منصتك.',
    'admin.home.goToDashboard': 'انتقل إلى لوحة التحكم',
    'admin.home.features.title': 'ميزات منصة المدير',
    'admin.home.features.subtitle': 'إدارة منصة الزراعة الخاصة بك بأدوات إدارية قوية',
    'admin.home.features.manageFarmers.title': 'إدارة المزارعين',
    'admin.home.features.manageFarmers.description': 'عرض جميع المزارعين المسجلين، واشتراكاتهم، وتتبع نشاطهم',
    'admin.home.features.trackProfits.title': 'تتبع الأرباح',
    'admin.home.features.trackProfits.description': 'راقب إجمالي الأرباح لكل مزارع وحلل الإيرادات عبر منصتك',
    'admin.home.features.analytics.title': 'التحليلات والتقارير',
    'admin.home.features.analytics.description': 'عرض توزيع الاشتراكات وإحصائيات المنصة',
    'admin.home.ai.badge': 'مساعد مدعوم بالذكاء الاصطناعي',
    'admin.home.ai.title': 'مساعد الدردشة بالذكاء الاصطناعي',
    'admin.home.ai.description': 'احصل على إجابات فورية ودعم مع مساعد الدردشة المدعوم بالذكاء الاصطناعي. اسأل عن إدارة المنصة، وتحليلات المزارعين، وخطط الاشتراك، أو أي استفسارات أخرى متعلقة بالمدير. المساعد متاح على مدار الساعة لمساعدتك في اتخاذ قرارات مستنيرة وإدارة منصتك بكفاءة.',
    'admin.home.ai.feature1.title': 'دعم إدارة المنصة',
    'admin.home.ai.feature1.description': 'احصل على المساعدة في إدارة المزارعين والاشتراكات والتحليلات',
    'admin.home.ai.feature2.title': 'رؤى التحليلات في الوقت الفعلي',
    'admin.home.ai.feature2.description': 'افهم مقاييس منصتك وبيانات الأداء',
    'admin.home.ai.feature3.title': 'دعم متاح على مدار الساعة',
    'admin.home.ai.feature3.description': 'الوصول إلى المساعدة في أي وقت وأي مكان مع ردود فورية',
    
    // Admin - Dashboard
    'admin.dashboard.title': 'لوحة تحكم المدير',
    'admin.dashboard.subtitle': 'إدارة المزارعين والاشتراكات وعرض إحصائيات النظام',
    'admin.dashboard.totalFarmers': 'إجمالي المزارعين',
    'admin.dashboard.registeredUsers': 'المستخدمون المسجلون',
    'admin.dashboard.subscribedFarmers': 'المزارعون المشتركون',
    'admin.dashboard.activeSubscriptions': 'الاشتراكات النشطة',
    'admin.dashboard.totalRevenue': 'إجمالي الإيرادات',
    'admin.dashboard.fromSubscriptions': 'من الاشتراكات',
    'admin.dashboard.totalFarmersProfit': 'إجمالي ربح المزارعين',
    'admin.dashboard.combinedProfit': 'الربح المجمع',
    'admin.dashboard.subscriptionPlansDistribution': 'توزيع خطط الاشتراك',
    'admin.dashboard.basicPlan': 'الخطة الأساسية',
    'admin.dashboard.proPlan': 'الخطة الاحترافية',
    'admin.dashboard.premiumPlan': 'الخطة المميزة',
    'admin.dashboard.farmers': 'مزارع',
    'admin.dashboard.farmersSubscriptions': 'المزارعون والاشتراكات',
    'admin.dashboard.loadingFarmers': 'جاري تحميل بيانات المزارعين...',
    'admin.dashboard.noFarmers': 'لم يتم العثور على مزارعين',
    'admin.dashboard.totalProfit': 'إجمالي الربح',
    'admin.dashboard.noSubscription': 'لا يوجد اشتراك',
    'admin.dashboard.systemNotifications': 'إشعارات النظام',
    'admin.dashboard.systemNotificationsSubtitle': 'عرض إشعارات وتنبيهات النظام',
    'admin.dashboard.noSystemNotifications': 'لا توجد إشعارات نظام',
    'admin.dashboard.noSystemNotificationsDesc': 'ستظهر إشعارات النظام هنا عندما تكون هناك تحديثات أو تنبيهات مهمة.',
    'admin.dashboard.settings.title': 'إعدادات المدير',
    'admin.dashboard.settings.subtitle': 'إدارة إعدادات وتفضيلات النظام',
    'admin.dashboard.settings.accountSettings': 'إعدادات الحساب',
    'admin.dashboard.settings.fullName': 'الاسم الكامل',
    'admin.dashboard.settings.email': 'البريد الإلكتروني',
    'admin.dashboard.settings.role': 'الدور',
    'admin.dashboard.settings.editProfile': 'تعديل الملف الشخصي',
    'admin.dashboard.settings.languageSettings': 'إعدادات اللغة',
    'admin.dashboard.settings.currentLanguage': 'اللغة الحالية',
    
    // Admin - Farmers Subscriptions Page
    'admin.farmers.viewAndManage': 'عرض وإدارة جميع المزارعين وتفاصيل اشتراكاتهم',
    'admin.farmers.subscriptionRevenue': 'إيرادات الاشتراك',
    'admin.farmers.fromActiveSubscriptions': 'من {count} اشتراك نشط',
    'admin.farmers.totalCropProfit': 'إجمالي ربح المحاصيل',
    'admin.farmers.fromAllCropSales': 'من مبيعات محاصيل جميع المزارعين',
    'admin.farmers.totalProfitSummary': 'ملخص إجمالي الربح',
    'admin.farmers.fromActivePayments': 'من دفعات الاشتراكات النشطة',
    'admin.farmers.cropProfit': 'ربح المحاصيل',
    'admin.farmers.fromCropSales': 'من مبيعات محاصيل المزارع',
    'admin.farmers.combinedTotal': 'الإجمالي المجمع',
    'admin.farmers.revenueDescription': 'الإيرادات من الاشتراكات النشطة - سعر اشتراك كل مزارع',
    'admin.farmers.totalRevenue': 'إجمالي الإيرادات',
    'admin.farmers.farmer': 'المزارع',
    'admin.farmers.email': 'البريد الإلكتروني',
    'admin.farmers.subscriptionPlan': 'خطة الاشتراك',
    'admin.farmers.subscriptionProfit': 'ربح الاشتراك',
    'admin.farmers.unknown': 'غير معروف',
    'admin.farmers.cropProfitDescription': 'الربح من مبيعات محاصيل المزارع - محسوب من كميات وأسعار المحاصيل',
    'admin.farmers.totalCropProfitLabel': 'إجمالي ربح المحاصيل',
    'admin.farmers.actions': 'الإجراءات',
    'admin.farmers.viewDetails': 'عرض التفاصيل',
    'admin.farmers.profitDistribution': 'توزيع الربح - {name}',
    'admin.farmers.loadingCrops': 'جاري تحميل المحاصيل...',
    'admin.farmers.totalProfitZero': 'إجمالي الربح: 0 جنيه',
    'admin.farmers.totalProfit': 'إجمالي الربح:',
    'admin.farmers.noCropsFound': 'لم يتم العثور على محاصيل لهذا المزارع',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get saved language from localStorage or default to English
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  useEffect(() => {
    // Update document direction and lang attribute
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    
    // Save to localStorage
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
